sonar.projectKey=heladeria-gestion
sonar.projectName=Heladeria Gestion
sonar.projectVersion=1.0
#Carpetas fuente a analizar
sonar.sources=frontend, backend
sonar.exclusions=**/node_modules/**,**/test_automation/**,**/*.min.js
# Carpeta de pruebas (la automatización de Nain)
sonar.tests=test_automation/tests
# Codificación
sonar.sourceEncoding=UTF-8
# Conexión de cobertura (Python/pytest)
sonar.python.coverage.reportPaths=coverage.xml