# Llave única y nombre de tu proyecto en SonarQube
sonar.projectKey=heladeria-backend
sonar.projectName=Backend Heladeria UPA
sonar.projectVersion=1.0

# Directorio a analizar (el punto significa "todo en esta carpeta")
sonar.sources=.

# Carpetas y archivos que SonarQube DEBE ignorar (Súper importante)
sonar.exclusions=node_modules/**, **/*.spec.ts, .env

# Codificación de los archivos
sonar.sourceEncoding=UTF-8